-- AlterTable
DO $$ BEGIN
  ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "costTotal" DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS "transportFee" DOUBLE PRECISION;
EXCEPTION WHEN undefined_table THEN NULL;
END $$;
